# Generated by Django 5.0 on 2024-02-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_pet_gender_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default=1, upload_to='dog_photo'),
            preserve_default=False,
        ),
    ]
